import { useEffect, useState } from 'react'
import { libraryApi, mediaApi, scheduleApi, systemApi, taskApi } from '@/lib/api'
import type { MediaAsset, TaskRun } from '@/types/crawler'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

const panel = 'glass-panel rounded-xl border border-cyber-border-subtle p-4 overflow-auto'
const value = (item: Record<string,unknown>, key:string) => item[key] == null ? '-' : String(item[key])

export function TaskCenter() {
  const [items,setItems]=useState<TaskRun[]>([]),[detail,setDetail]=useState<Record<string,unknown>|null>(null)
  const load=()=>taskApi.list().then(r=>setItems(r.data.items as unknown as TaskRun[]))
  const inspect=(id:string)=>Promise.all([taskApi.detail(id),taskApi.items(id),taskApi.logs(id)]).then(([d,a,b])=>setDetail({task:d.data,stages:a.data.stages,items:a.data.items,logs:b.data.logs}))
  useEffect(()=>{load();const id=setInterval(load,3000);return()=>clearInterval(id)},[])
  return <div className={panel}><h2 className="font-mono text-cyber-neon-cyan mb-3">任务中心</h2>
    <div className="space-y-2">{items.map(x=><div key={x.run_id} className="border border-cyber-border-subtle rounded-lg p-3 flex justify-between gap-3">
      <button className="text-left" onClick={()=>inspect(x.run_id)}><div className="font-mono text-sm">{x.crawler_type} · {x.stage}</div><div className="text-xs text-cyber-text-muted">{x.run_id} · {x.status}</div></button>
      <div className="flex gap-2"><Button size="sm" onClick={()=>taskApi.pause(x.run_id).then(load)}>暂停</Button><Button size="sm" onClick={()=>(x.status==='waiting_for_login'?taskApi.continueAfterLogin(x.run_id):taskApi.resume(x.run_id)).then(load)}>{x.status==='waiting_for_login'?'登录后继续':'继续'}</Button><Button size="sm" onClick={()=>taskApi.retry(x.run_id).then(load)}>重试</Button><Button size="sm" variant="destructive" onClick={()=>taskApi.cancel(x.run_id).then(load)}>取消</Button></div>
    </div>)}</div>{detail?<pre className="mt-4 text-xs whitespace-pre-wrap bg-black/20 p-3 rounded-lg max-h-80 overflow-auto">{JSON.stringify(detail,null,2)}</pre>:null}</div>
}

export function ContentLibrary() {
  const [items,setItems]=useState<Record<string,unknown>[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<Record<string,unknown>|null>(null),[kind,setKind]=useState<'awemes'|'creators'|'topics'|'comments'|'transcripts'>('awemes')
  const [creator,setCreator]=useState(''),[topic,setTopic]=useState(''),[minLikes,setMinLikes]=useState(''),[stats,setStats]=useState<Record<string,unknown>|null>(null)
  const load=()=>kind==='awemes'?libraryApi.awemes(q,{creator_hash:creator,source_topic:topic,min_likes:minLikes||undefined}).then(r=>setItems(r.data.items as unknown as Record<string,unknown>[])):libraryApi[kind](q).then(r=>setItems(r.data.items))
  useEffect(()=>{void load();libraryApi.stats().then(r=>setStats(r.data)).catch(()=>setStats(null))},[])
  const change=(next:typeof kind)=>{setKind(next);setSelected(null);setTimeout(()=>libraryApi[next](q).then(r=>setItems(r.data.items)),0)}
  const counts=(stats?.counts||{}) as Record<string,unknown>
  return <div className={`${panel} space-y-3`}><h2 className="font-mono text-cyber-neon-cyan">内容库</h2><div className="grid grid-cols-3 md:grid-cols-6 gap-2 text-xs">{Object.entries(counts).map(([k,v])=><div key={k} className="border border-cyber-border-subtle rounded-lg p-2"><div className="text-cyber-text-muted">{k}</div><div className="text-lg text-cyber-neon-green">{String(v)}</div></div>)}</div><div className="flex gap-2 flex-wrap">{(['awemes','creators','topics','comments','transcripts'] as const).map(x=><Button key={x} size="sm" variant={kind===x?'default':'outline'} onClick={()=>change(x)}>{{awemes:'作品',creators:'账号',topics:'话题',comments:'评论',transcripts:'字幕'}[x]}</Button>)}</div><div className="flex gap-2 flex-wrap"><Input className="min-w-48 flex-1" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索当前分类"/>{kind==='awemes'?<><Input className="w-44" value={creator} onChange={e=>setCreator(e.target.value)} placeholder="作者 hash"/><Input className="w-40" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="来源话题"/><Input className="w-28" type="number" value={minLikes} onChange={e=>setMinLikes(e.target.value)} placeholder="最低点赞"/></>:null}<Button onClick={load}>筛选</Button>{kind==='awemes'?<><a href={libraryApi.exportUrl('jsonl',q)}><Button variant="outline">导出 JSONL</Button></a><a href={libraryApi.exportUrl('csv',q)}><Button variant="outline">导出 CSV</Button></a></>:null}</div>
    <div className="grid md:grid-cols-2 gap-2">{items.map((x,i)=><button key={String(x.aweme_id||x.creator_hash||x.topic_id||x.comment_id||i)} onClick={()=>kind==='awemes'&&libraryApi.detail(String(x.aweme_id)).then(r=>setSelected(r.data))} className="text-left border border-cyber-border-subtle p-3 rounded-lg"><div className="line-clamp-2 text-sm">{String(x.title||x.nickname||x.name||x.content||x.full_text||'未命名')}</div><div className="text-xs text-cyber-text-muted mt-1">{kind==='awemes'?`赞 ${x.liked_count??'-'} · 评 ${x.comment_count??'-'}`:`${x.status||x.creator_hash||x.topic_id||x.aweme_id||''}`}</div></button>)}</div>
    {selected?<AwemeInspector data={selected}/>:null}</div>
}

function AwemeInspector({data}:{data:Record<string,unknown>}) {
  const aweme=(data.aweme||{}) as Record<string,unknown>, metrics=(data.metrics||[]) as Record<string,unknown>[], comments=(data.comments||[]) as Record<string,unknown>[], transcript=data.transcript as Record<string,unknown>|null
  const maxLike=Math.max(1,...metrics.map(x=>Number(x.liked_count)||0))
  let segments:Record<string,unknown>[]=[]
  try { segments=transcript?.segments ? JSON.parse(String(transcript.segments)) : [] } catch { /* malformed stored transcript */ }
  return <div className="space-y-4 border border-cyber-border-subtle rounded-xl p-4 bg-black/20">
    <div><h3 className="text-base text-cyber-neon-cyan">{value(aweme,'title')}</h3><p className="text-sm whitespace-pre-wrap mt-2">{value(aweme,'desc')}</p><div className="text-xs text-cyber-text-muted mt-2">赞 {value(aweme,'liked_count')} · 收藏 {value(aweme,'collected_count')} · 评论 {value(aweme,'comment_count')} · 分享 {value(aweme,'share_count')} · 播放 {value(aweme,'play_count')}</div></div>
    <section><h4 className="text-sm mb-2">指标趋势</h4><div className="space-y-1">{metrics.map((x,i)=><div key={i} className="flex items-center gap-2 text-xs"><span className="w-32 text-cyber-text-muted">{new Date(Number(x.observed_at)*1000).toLocaleString()}</span><div className="h-2 bg-cyber-neon-cyan rounded" style={{width:`${Math.max(2,(Number(x.liked_count)||0)/maxLike*60)}%`}}/><span>{value(x,'liked_count')} 赞</span></div>)}</div></section>
    <section><h4 className="text-sm mb-2">字幕时间轴 · {transcript?value(transcript,'status'):'无字幕'}</h4>{segments.length?<div className="max-h-52 overflow-auto space-y-1">{segments.map((x,i)=><div key={i} className="text-xs"><span className="text-cyber-neon-green mr-2">{(Number(x.start_ms||0)/1000).toFixed(1)}s</span>{value(x,'text')}</div>)}</div>:<p className="text-xs text-cyber-text-muted whitespace-pre-wrap">{transcript?value(transcript,'full_text'):'暂无可用字幕'}</p>}</section>
    <section><h4 className="text-sm mb-2">评论树</h4><div className="space-y-2 max-h-72 overflow-auto">{comments.map(root=><div key={String(root.comment_id)} className="border-l-2 border-cyber-neon-cyan pl-3 text-xs"><div>{value(root,'nickname')}：{value(root,'content')} · ♡ {value(root,'like_count')}</div>{((root.replies||[]) as Record<string,unknown>[]).map(reply=><div key={String(reply.comment_id)} className="ml-5 mt-1 text-cyber-text-muted">↳ {value(reply,'nickname')}：{value(reply,'content')}</div>)}</div>)}</div></section>
  </div>
}

export function MediaLibrary() {
  const [items,setItems]=useState<MediaAsset[]>([]);const load=()=>mediaApi.list().then(r=>setItems(r.data.items));useEffect(()=>{void load()},[])
  return <div className={panel}><h2 className="font-mono text-cyber-neon-cyan mb-3">媒体库</h2><div className="grid md:grid-cols-2 gap-3">{items.map(x=><div key={x.asset_id} className="border border-cyber-border-subtle rounded-lg p-3"><div>{x.aweme_id} · {x.kind}</div><div className="text-xs text-cyber-text-muted">{x.status} · {(x.size_bytes/1048576).toFixed(1)} MB</div>{x.status==='completed'?<video className="w-full mt-2" controls src={mediaApi.streamUrl(x.asset_id)}/>:null}<Button className="mt-2" size="sm" variant="destructive" onClick={()=>confirm('确认删除这个正式媒体文件？')&&mediaApi.remove(x.asset_id).then(load)}>删除</Button></div>)}</div></div>
}

export function Schedules() {
  const [items,setItems]=useState<Record<string,unknown>[]>([]),[name,setName]=useState('每日增量'),[source,setSource]=useState(''),[mode,setMode]=useState<'creator'|'topic'>('creator'),[interval,setIntervalType]=useState<'once'|'hourly'|'daily'>('daily'),[runAt,setRunAt]=useState(''),[editingId,setEditingId]=useState<string|null>(null);const load=()=>scheduleApi.list().then(r=>setItems(r.data.items));useEffect(()=>{void load()},[])
  const payload=(enabled=true)=>({name,enabled,platform:'dy',crawler_type:mode,source,interval_type:interval,interval_value:1,run_at:interval==='once'?new Date(runAt).toISOString():null,timezone:'Asia/Shanghai',config:{platform:'dy',crawler_type:mode,creator_ids:mode==='creator'?source:'',topics:mode==='topic'?source:'',incremental:true,save_option:'jsonl'}})
  const rowPayload=(x:Record<string,unknown>,enabled:boolean)=>{let saved:Record<string,unknown>={};try{saved=JSON.parse(String(x.config_json||'{}'))}catch{/* malformed legacy schedule */}return {name:String(x.name),enabled,platform:'dy',crawler_type:String(x.crawler_type),source:String(x.source),interval_type:String(x.interval_type),interval_value:Number(x.interval_value)||1,run_at:x.run_at||null,timezone:String(x.timezone||'Asia/Shanghai'),config:saved}}
  const save=()=>{const action=editingId?scheduleApi.update(editingId,payload()):scheduleApi.create(payload());return action.then(()=>{setEditingId(null);setSource('');return load()})}
  const edit=(x:Record<string,unknown>)=>{setEditingId(String(x.schedule_id));setName(String(x.name));setSource(String(x.source));setMode(String(x.crawler_type) as 'creator'|'topic');setIntervalType(String(x.interval_type) as 'once'|'hourly'|'daily');setRunAt(x.run_at?new Date(String(x.run_at)).toISOString().slice(0,16):'')}
  return <div className={`${panel} space-y-3`}><h2 className="font-mono text-cyber-neon-cyan">定时计划</h2><div className="grid md:grid-cols-6 gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="计划名称"/><select className="bg-cyber-bg-tertiary border border-cyber-border-subtle rounded-md px-2 text-xs" value={mode} onChange={e=>setMode(e.target.value as 'creator'|'topic')}><option value="creator">账号</option><option value="topic">话题</option></select><select className="bg-cyber-bg-tertiary border border-cyber-border-subtle rounded-md px-2 text-xs" value={interval} onChange={e=>setIntervalType(e.target.value as 'once'|'hourly'|'daily')}><option value="once">单次</option><option value="hourly">每小时</option><option value="daily">每天</option></select><Input value={source} onChange={e=>setSource(e.target.value)} placeholder="账号 URL / 话题"/>{interval==='once'?<Input type="datetime-local" value={runAt} onChange={e=>setRunAt(e.target.value)}/>:<span/>}<Button disabled={!source.trim()||(interval==='once'&&!runAt)} onClick={save}>{editingId?'保存修改':'创建计划'}</Button></div>{editingId?<Button size="sm" variant="outline" onClick={()=>{setEditingId(null);setSource('')}}>取消编辑</Button>:null}{items.map(x=><div key={String(x.schedule_id)} className="border border-cyber-border-subtle rounded-lg p-3 flex justify-between"><span>{String(x.name)} · {String(x.interval_type)} · {String(x.enabled)==='1'?'启用':'停用'} · {String(x.next_run_at??'已结束')}</span><div className="flex gap-2"><Button size="sm" onClick={()=>edit(x)}>编辑</Button><Button size="sm" onClick={()=>scheduleApi.run(String(x.schedule_id)).then(load)}>立即运行</Button><Button size="sm" onClick={()=>scheduleApi.update(String(x.schedule_id),rowPayload(x,!Number(x.enabled))).then(load)}>{Number(x.enabled)?'停用':'启用'}</Button><Button size="sm" variant="destructive" onClick={()=>confirm('删除计划不会删除历史任务，确认继续？')&&scheduleApi.remove(String(x.schedule_id)).then(load)}>删除</Button></div></div>)}</div>
}

export function HealthPage(){const [data,setData]=useState<Record<string,unknown>|null>(null);useEffect(()=>{Promise.all([systemApi.health(),systemApi.storage()]).then(([h,s])=>setData({health:h.data,storage:s.data}))},[]);return <div className={panel}><h2 className="font-mono text-cyber-neon-cyan mb-3">系统健康</h2><pre className="text-xs whitespace-pre-wrap">{JSON.stringify(data,null,2)}</pre></div>}
