import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Link2, Loader2, Play, RefreshCw, Server, Unlink } from 'lucide-react'
import { toast } from 'sonner'
import { remoteApi } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

type Item = Record<string, unknown>
const surface = 'glass-panel rounded-xl border border-cyber-border-subtle p-5 overflow-auto'
const statusTone = (status:unknown) => ['connected','logged_in','completed','online'].includes(String(status)) ? 'text-cyber-neon-green' : ['failed','risk_controlled','captcha_required'].includes(String(status)) ? 'text-cyber-neon-pink' : 'text-cyber-neon-orange'

export function RemoteWorkspace() {
  const [workers,setWorkers]=useState<Item[]>([]),[connections,setConnections]=useState<Item[]>([]),[runs,setRuns]=useState<Item[]>([])
  const [session,setSession]=useState<Item|null>(null),[qrUrl,setQrUrl]=useState(''),[busy,setBusy]=useState(false)
  const [connectionId,setConnectionId]=useState(''),[mode,setMode]=useState('search'),[source,setSource]=useState(''),[count,setCount]=useState(30)
  const [resultKind,setResultKind]=useState('aweme'),[results,setResults]=useState<Item[]>([])
  const connected=useMemo(()=>connections.filter(x=>x.status==='connected'),[connections])
  const load=async()=>{const [w,c,r]=await Promise.all([remoteApi.workers(),remoteApi.connections(),remoteApi.runs()]);setWorkers(w.data.items);setConnections(c.data.items);setRuns(r.data.items as unknown as Item[]);if(!connectionId&&c.data.items[0])setConnectionId(String(c.data.items[0].connection_id))}
  useEffect(()=>{load().catch(()=>undefined);const timer=setInterval(()=>load().catch(()=>undefined),5000);return()=>clearInterval(timer)},[])
  useEffect(()=>{if(!session?.login_session_id)return;const timer=setInterval(async()=>{const response=await remoteApi.login(String(session.login_session_id));setSession(response.data);if(response.data.qr_available&&!qrUrl){const image=await remoteApi.qr(String(session.login_session_id));setQrUrl(URL.createObjectURL(image.data))}if(['logged_in','expired','cancelled','failed','captcha_required','risk_controlled'].includes(response.data.status)){void load()}},1000);return()=>clearInterval(timer)},[session?.login_session_id,qrUrl])
  useEffect(()=>()=>{if(qrUrl)URL.revokeObjectURL(qrUrl)},[qrUrl])
  const startLogin=async()=>{if(!workers[0])return;setBusy(true);try{const r=await remoteApi.createLogin();setQrUrl('');setSession(r.data)}catch{toast.error('无法创建登录会话，请确认 Worker 在线')}finally{setBusy(false)}}
  const refresh=async()=>{if(!session)return;await remoteApi.refreshLogin(String(session.login_session_id));if(qrUrl)URL.revokeObjectURL(qrUrl);setQrUrl('');setSession({...session,status:'queued'})}
  const reconnect=async(id:string)=>{const response=await remoteApi.reconnect(id);setQrUrl('');setSession(response.data)}
  const createRun=async()=>{if(!connectionId||!source.trim())return;const sourceKey={search:'keywords',topic:'topics',detail:'specified_ids',creator:'creator_ids'}[mode]||'keywords';await remoteApi.createRun({connection_id:connectionId,crawler_type:mode,[sourceKey]:source,max_notes_count:count,enable_comments:true,enable_sub_comments:true,max_comments_count:0,enable_creator_profile:true,enable_native_subtitle:true,enable_asr:true,download_media:false});toast.success('远程采集任务已进入队列');setSource('');void load()}
  const loadResults=(kind=resultKind)=>remoteApi.results(kind).then(r=>setResults(r.data.items))
  return <div className="grid xl:grid-cols-[minmax(320px,0.82fr)_minmax(520px,1.4fr)] gap-4 min-h-0 overflow-auto">
    <section className={`${surface} space-y-5`}><div><p className="text-xs font-mono text-cyber-text-muted">DOUYIN CONNECTION</p><h2 className="text-lg font-semibold mt-1">抖音账号连接</h2><p className="text-xs text-cyber-text-muted mt-1">二维码来自抓取机 Chrome；Cookie、Profile 和 CDP 信息不会发送到网站。</p></div>
      <div className="border-y border-cyber-border-subtle py-3 flex items-center justify-between"><span className="flex items-center gap-2 text-sm"><Server className="w-4 h-4"/>执行设备</span><span className={`text-xs font-mono ${statusTone(workers[0]?.status)}`}>{workers[0]?`${workers[0].name} · ${workers[0].status}`:'暂无可用 Worker'}</span></div>
      {connections.map(x=><div key={String(x.connection_id)} className="flex items-center justify-between gap-3"><div><div className="text-sm">{String(x.masked_nickname||'待连接账号')}</div><div className={`text-xs font-mono ${statusTone(x.status)}`}>{String(x.status)} · {String(x.creator_hash||'尚未验证')}</div></div><div className="flex gap-1">{['session_expired','verification_required','risk_controlled'].includes(String(x.status))?<Button size="sm" onClick={()=>reconnect(String(x.connection_id))}>重新扫码</Button>:null}<Button size="sm" variant="outline" onClick={()=>confirm('断开后会删除抓取机上的专用浏览器 Profile，历史数据仍保留。确认继续？')&&remoteApi.disconnect(String(x.connection_id)).then(load)}><Unlink className="w-3.5 h-3.5 mr-1"/>断开</Button></div></div>)}
      {!session||['logged_in','expired','cancelled','failed'].includes(String(session.status))?<Button className="w-full" disabled={!workers[0]||busy} onClick={startLogin}>{busy?<Loader2 className="w-4 h-4 mr-2 animate-spin"/>:<Link2 className="w-4 h-4 mr-2"/>}连接抖音账号</Button>:<div className="space-y-3 text-center"><div className="aspect-square max-w-60 mx-auto bg-white rounded-xl p-3 flex items-center justify-center">{qrUrl?<img src={qrUrl} className="w-full h-full object-contain" alt="抖音登录二维码"/>:<Loader2 className="w-8 h-8 text-black animate-spin"/>}</div><div className={statusTone(session.status)}>{String(session.status)==='qr_scanned'?'已扫码，请在手机确认':String(session.status)==='qr_ready'?'请使用抖音 App 扫码':String(session.status)}</div><div className="flex justify-center gap-2"><Button size="sm" variant="outline" onClick={refresh}><RefreshCw className="w-3.5 h-3.5 mr-1"/>刷新</Button><Button size="sm" variant="outline" onClick={()=>remoteApi.cancelLogin(String(session.login_session_id)).then(()=>setSession(null))}>取消</Button></div></div>}
      {session&&['captcha_required','risk_controlled'].includes(String(session.status))?<p className="flex gap-2 text-xs text-cyber-neon-orange"><AlertTriangle className="w-4 h-4 shrink-0"/>抓取机需要管理员完成人工验证；系统不会绕过验证码。</p>:null}
    </section>
    <section className={`${surface} space-y-5`}><div><p className="text-xs font-mono text-cyber-text-muted">REMOTE CRAWL</p><h2 className="text-lg font-semibold mt-1">新建远程采集</h2></div><div className="grid md:grid-cols-[1fr_150px_100px] gap-2"><select className="bg-cyber-bg-tertiary border border-cyber-border-subtle rounded-md px-3 text-sm" value={connectionId} onChange={e=>setConnectionId(e.target.value)}><option value="">选择已连接账号</option>{connected.map(x=><option key={String(x.connection_id)} value={String(x.connection_id)}>{String(x.masked_nickname||x.connection_id)}</option>)}</select><select className="bg-cyber-bg-tertiary border border-cyber-border-subtle rounded-md px-3 text-sm" value={mode} onChange={e=>setMode(e.target.value)}><option value="search">关键词</option><option value="topic">真实话题</option><option value="detail">指定视频</option><option value="creator">指定账号</option></select><Input type="number" min={1} max={10000} value={count} onChange={e=>setCount(Number(e.target.value))}/></div><div className="flex gap-2"><Input value={source} onChange={e=>setSource(e.target.value)} placeholder="输入关键词、话题名称/URL/ID、视频 URL 或账号 URL"/><Button disabled={!connectionId||!source.trim()} onClick={createRun}><Play className="w-4 h-4 mr-1"/>开始</Button></div>
      <div className="border-t border-cyber-border-subtle pt-4"><div className="flex justify-between text-xs text-cyber-text-muted mb-2"><span>最近任务</span><span>{runs.length} 条</span></div><div className="space-y-2">{runs.slice(0,12).map(x=><div key={String(x.run_id)} className="grid grid-cols-[1fr_auto] gap-3 py-2 border-b border-cyber-border-subtle/50"><div><div className="text-sm">{String(x.stage)} · <span className={statusTone(x.status)}>{String(x.status)}</span></div><div className="text-[11px] font-mono text-cyber-text-muted truncate">{String(x.run_id)}</div></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>remoteApi.control(String(x.run_id),'pause').then(load)}>暂停</Button><Button size="sm" variant="outline" onClick={()=>remoteApi.control(String(x.run_id),'resume').then(load)}>继续</Button><Button size="sm" variant="destructive" onClick={()=>remoteApi.control(String(x.run_id),'cancel').then(load)}>取消</Button></div></div>)}</div></div>
      <div className="border-t border-cyber-border-subtle pt-4 space-y-3"><div className="flex gap-2 flex-wrap">{(['aweme','comment','transcript','creator','topic','media'] as const).map(kind=><Button key={kind} size="sm" variant={resultKind===kind?'default':'outline'} onClick={()=>{setResultKind(kind);void loadResults(kind)}}>{{aweme:'作品',comment:'评论',transcript:'字幕',creator:'账号',topic:'话题',media:'媒体'}[kind]}</Button>)}<Button size="sm" variant="outline" onClick={()=>loadResults()}><RefreshCw className="w-3.5 h-3.5"/></Button></div><div className="max-h-72 overflow-auto space-y-2">{results.map(row=>{const payload=(row.payload||{}) as Item;return <div key={String(row.source_event_id)} className="py-2 border-b border-cyber-border-subtle/50 text-xs"><div className="text-cyber-text-muted font-mono">{String(row.entity_id)}</div><div className="mt-1 whitespace-pre-wrap line-clamp-4">{String(payload.title||payload.desc||payload.content||payload.full_text||payload.masked_nickname||payload.name||payload.status||'已同步')}</div>{resultKind==='media'&&payload.status==='completed'?<video controls preload="metadata" className="w-full mt-2" src={remoteApi.mediaUrl(String(row.entity_id))}/>:null}</div>})}</div></div>
    </section>
  </div>
}

export function WorkerAdmin() {
  const [workers,setWorkers]=useState<Item[]>([]),[code,setCode]=useState('')
  const load=()=>remoteApi.adminWorkers().then(r=>setWorkers(r.data.items));useEffect(()=>{void load()},[])
  return <div className={`${surface} space-y-4`}><div><p className="text-xs font-mono text-cyber-text-muted">ADMIN</p><h2 className="text-lg font-semibold">Worker 管理</h2></div><Button onClick={()=>remoteApi.enrollment().then(r=>setCode(r.data.enrollment_code))}>生成 10 分钟注册码</Button>{code?<pre className="p-3 bg-black/20 rounded-lg text-xs whitespace-pre-wrap break-all">{code}</pre>:null}{workers.map(x=><div key={String(x.worker_id)} className="flex justify-between border-t border-cyber-border-subtle pt-3"><span>{String(x.name)}</span><span className={statusTone(x.status)}>{String(x.status)} · {String(x.last_heartbeat_at||'-')}</span></div>)}</div>
}
