import { useState, type FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { KeyRound, LogOut } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useAuth } from '@/contexts/AuthContext'

export default function ChangePasswordPage(){const{user,changePassword,logout}=useAuth();const navigate=useNavigate();const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);if(!user)return <Navigate to="/login" replace/>;if(!user.must_change_password)return <Navigate to="/" replace/>;const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await changePassword(password,confirm);toast.success('正式密码已设置');navigate('/',{replace:true})}catch(error:any){toast.error(error?.response?.data?.detail?.user_message||'密码修改失败')}finally{setBusy(false)}};return <div className="grid min-h-screen place-items-center bg-slate-100 px-4"><main className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-semibold text-teal-700">首次登录</p><h1 className="mt-1 text-2xl font-semibold">设置正式密码</h1><p className="mt-2 text-sm leading-6 text-slate-600">临时密码只能用于激活账号。设置正式密码后，当前临时会话将被替换。</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-medium">新密码<Input type="password" autoComplete="new-password" className="mt-2 h-11" value={password} onChange={e=>setPassword(e.target.value)}/><span className="mt-2 block text-xs font-normal text-slate-500">12～128 个字符，不能与用户名或临时密码相同。</span></label><label className="block text-sm font-medium">确认新密码<Input type="password" autoComplete="new-password" className="mt-2 h-11" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><Button className="h-11 w-full" disabled={busy||password.length<12||password!==confirm}><KeyRound/>保存并进入工作台</Button></form><Button variant="ghost" className="mt-4 w-full" onClick={()=>logout().then(()=>navigate('/login'))}><LogOut/>退出登录</Button></main></div>}
