import { useEffect, useState } from 'react'
import { Clapperboard, FileImage, FileMusic, FileVideo, HardDrive, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { EmptyState, PageHeader, StatusBadge, Surface } from '@/components/product/Primitives'
import { mediaApi, remoteApi, systemApi } from '@/lib/api'
import { useCapabilities } from '@/hooks/useProduct'
import { formatBytes, formatDuration } from '@/lib/presentation'
import type { MediaSummary } from '@/types/product'

export default function MediaPage(){const capabilities=useCapabilities();const remote=capabilities.data?.features.remote_worker;const [items,setItems]=useState<MediaSummary[]>([]),[storage,setStorage]=useState<Record<string,number>>({}),[loading,setLoading]=useState(false);const load=async()=>{setLoading(true);try{if(remote){const response=await remoteApi.results('media');setItems(response.data.items.map((row:Record<string,unknown>)=>({...((row.payload||{})as Record<string,unknown>),asset_id:row.entity_id})))}else{const response=await mediaApi.list();setItems(response.data.items)}const storageResponse=await systemApi.storage();setStorage(storageResponse.data)}finally{setLoading(false)}};useEffect(()=>{if(capabilities.data)void load()},[remote,capabilities.data]);const remove=async(item:MediaSummary)=>{if(remote){toast.error('远程媒体删除需要由网站控制中心授权');return}if(!confirm('确认删除这个正式媒体文件？数据库记录会保留，之后可以重新下载。'))return;await mediaApi.remove(item.asset_id);toast.success('媒体文件已删除');await load()};return <div><PageHeader eyebrow="数据" title="媒体库" description="正式媒体保存在抓取设备。播放使用授权 Range 流，不生成永久公开地址。" actions={<Button variant="outline" onClick={load}><RefreshCw className={loading?'animate-spin':''}/>刷新</Button>}/><div className="mb-4 grid gap-3 sm:grid-cols-3"><Surface className="p-4"><p className="flex items-center gap-2 text-xs text-slate-500"><HardDrive className="h-4 w-4"/>媒体库使用量</p><p className="mt-2 text-xl font-semibold">{formatBytes(storage.media_bytes)}</p></Surface><Surface className="p-4"><p className="text-xs text-slate-500">磁盘剩余</p><p className="mt-2 text-xl font-semibold">{formatBytes(storage.free_bytes)}</p></Surface><Surface className="p-4"><p className="text-xs text-slate-500">媒体资产</p><p className="mt-2 text-xl font-semibold">{items.length}</p></Surface></div>{items.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><MediaCard key={item.asset_id} item={item} remote={Boolean(remote)} onDelete={()=>remove(item)}/>)}</div>:<Surface><EmptyState icon={<Clapperboard/>} title="还没有正式媒体" description="新建任务时开启正式媒体下载，完成的视频、图文、封面和音乐会出现在这里。"/></Surface>}</div>}
function MediaCard({item,remote,onDelete}:{item:MediaSummary;remote:boolean;onDelete:()=>void}){const Icon=item.kind==='video'?FileVideo:item.kind==='music'?FileMusic:FileImage;const playable=item.status==='completed'&&item.kind==='video';const url=remote?remoteApi.mediaUrl(item.asset_id):mediaApi.streamUrl(item.asset_id);return <Surface className="overflow-hidden"><div className="relative grid aspect-video place-items-center bg-slate-950 text-slate-500">{playable?<video className="h-full w-full object-contain" controls preload="metadata" src={url}/>:<Icon className="h-10 w-10"/>}<span className="absolute left-3 top-3"><StatusBadge status={item.status} label={({completed:'下载完成',downloading:'下载中',partial:'续传中',waiting_for_space:'配额暂停',failed:'下载失败',deleted:'已删除'}as Record<string,string>)[item.status]||item.status}/></span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-950">作品 {item.aweme_id}</p><p className="mt-1 text-xs text-slate-500">{item.kind} · {item.quality||'默认质量'} · {formatBytes(item.size_bytes)}</p></div>{item.sha256?<ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600"/>:null}</div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{item.duration_ms?formatDuration(item.duration_ms/1000):item.mime_type||'媒体文件'}</span>{item.status!=='deleted'?<Button size="sm" variant="ghost" onClick={onDelete}><Trash2/>删除</Button>:null}</div></div></Surface>}
