import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, Check, Clipboard, Download, FileText, MessageSquareText, Mic2, Pause, Play, RotateCcw, Square, TerminalSquare } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { ErrorState, PageHeader, ProgressBar, StatusBadge, Surface } from '@/components/product/Primitives'
import { remoteApi, taskApi } from '@/lib/api'
import { useCapabilities } from '@/hooks/useProduct'
import { actionLabels, formatBytes, formatDate, formatDuration, stageLabels } from '@/lib/presentation'
import type { TaskAllowedAction, TaskSummary } from '@/types/product'

type Item = Record<string, unknown>
const stageIcons: Record<string, typeof FileText> = { discover: FileText, detail: FileText, creator: FileText, comments: MessageSquareText, native_transcript: FileText, media_download: Download, asr: Mic2, finalize: Check }

export default function TaskDetailPage() {
  const { runId = '' } = useParams(); const navigate = useNavigate(); const capabilities = useCapabilities(); const remote = capabilities.data?.features.remote_worker
  const [run, setRun] = useState<TaskSummary | null>(null), [stages, setStages] = useState<Item[]>([]), [items, setItems] = useState<Item[]>([]), [logs, setLogs] = useState<Item[]>([]), [showLogs, setShowLogs] = useState(false), [error, setError] = useState('')
  const load = async () => {
    try {
      if (remote) { const [detail,itemResponse,logResponse] = await Promise.all([remoteApi.run(runId), remoteApi.runItems(runId), remoteApi.runLogs(runId)]); setRun(detail.data); setItems(itemResponse.data.items); setLogs(logResponse.data.logs); setStages([]) }
      else { const [detail,itemResponse,logResponse] = await Promise.all([taskApi.detail(runId),taskApi.items(runId),taskApi.logs(runId)]); setRun(detail.data); setStages(itemResponse.data.stages); setItems(itemResponse.data.items); setLogs(logResponse.data.logs) }
    } catch { setError('找不到这个任务，或当前账号没有查看权限。') }
  }
  useEffect(() => { if (capabilities.data) void load(); const timer=setInterval(() => { if (capabilities.data) void load() },5000); return()=>clearInterval(timer) },[runId,remote,capabilities.data])
  const control = async (action:TaskAllowedAction) => {
    if (!run) return
    if (action === 'view_results') { navigate('/library'); return } if (action === 'rerun') { navigate(`/crawl/new?mode=${run.crawler_type}`); return } if (action === 'reconnect') { navigate('/connect'); return }
    if (action === 'cancel' && !confirm('确认取消任务？已经保存的数据不会删除。')) return
    try { if(remote) await remoteApi.control(runId,action==='retry_failed'?'retry-failed':action as 'pause'|'resume'|'cancel'); else if(action==='pause')await taskApi.pause(runId);else if(action==='resume')await taskApi.resume(runId);else if(action==='continue_after_login')await taskApi.continueAfterLogin(runId);else if(action==='cancel')await taskApi.cancel(runId);else if(action==='retry_failed')await taskApi.retry(runId);toast.success('操作已提交');await load()} catch {toast.error('当前状态不允许这个操作')}
  }
  if (error) return <ErrorState title="无法打开任务" description={error}/>
  if (!run) return <div className="h-96 animate-pulse rounded-xl bg-slate-100"/>
  const timeline: Item[] = stages.length ? stages : Object.entries(run.stage_counts || {}).map(([stage,value]) => ({stage,...value}))
  return <div><button onClick={() => navigate('/tasks')} className="mb-4 inline-flex min-h-10 items-center gap-2 text-sm font-medium text-slate-600 hover:text-teal-800"><ArrowLeft className="h-4 w-4"/>返回任务中心</button><PageHeader eyebrow="任务详情" title={run.display_name} description={`${run.account_label} · 创建于 ${formatDate(run.created_at)}`} actions={<div className="flex flex-wrap gap-2">{run.allowed_actions.filter(a=>!['view_failures','view_error'].includes(a)).map(action=><Button key={action} variant={action==='cancel'?'ghost':action==='retry_failed'?'outline':'default'} onClick={()=>control(action)}>{action==='pause'?<Pause/>:action==='resume'||action==='continue_after_login'?<Play/>:action==='cancel'?<Square/>:action==='retry_failed'||action==='rerun'?<RotateCcw/>:null}{actionLabels[action]}</Button>)}</div>}/>
    {run.error ? <div className="mb-4 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-700"/><div><p className="text-sm font-semibold text-amber-950">{run.error.user_message}</p>{run.error.recoverable ? <p className="mt-1 text-xs text-amber-800">这个问题可以恢复，已采集数据不会回滚。</p> : null}</div></div> : null}
    <div className="grid gap-4 xl:grid-cols-[1.45fr_.75fr]"><div className="space-y-4"><Surface className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-950">总体进度</p><p className="mt-1 text-xs text-slate-500">当前阶段：{run.stage_label}</p></div><StatusBadge status={run.status} label={run.status_label}/></div><div className="mt-5"><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">已完成 {run.progress.completed} 个作品</span><strong className="tabular-nums">{run.progress.percent}%</strong></div><ProgressBar value={run.progress.percent}/></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="运行时间" value={formatDuration(run.elapsed_seconds)}/><Metric label="预计剩余" value={formatDuration(run.estimated_remaining_seconds)}/><Metric label="已下载" value={formatBytes(run.downloaded_bytes)}/><Metric label="媒体配额" value={formatBytes(run.task_media_quota_bytes)}/></div></Surface>
      <Surface className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">阶段时间线</h2><p className="mt-1 text-xs text-slate-500">每个阶段独立保存状态，失败不会回滚已经完成的数据。</p></div><div className="p-5">{timeline.map((stage,index)=>{const key=String(stage.stage);const Icon=stageIcons[key]||FileText;const status=String(stage.status||'queued');return <div key={key} className="relative flex gap-4 pb-6 last:pb-0">{index<timeline.length-1?<span className="absolute left-[17px] top-9 h-[calc(100%-20px)] w-px bg-slate-200"/>:null}<span className={`relative z-10 grid h-9 w-9 shrink-0 place-items-center rounded-full ${status==='completed'?'bg-emerald-100 text-emerald-700':status==='running'?'bg-sky-100 text-sky-700 ring-4 ring-sky-50':status==='failed'||status==='partial'?'bg-red-100 text-red-700':'bg-slate-100 text-slate-400'}`}><Icon className="h-4 w-4"/></span><div className="min-w-0 flex-1 pt-1"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-900">{String(stage.label||stageLabels[key]||key)}</p><span className="text-xs text-slate-500">完成 {String(stage.completed_count??stage.completed??0)} · 失败 {String(stage.failed_count??stage.failed??0)}</span></div><p className="mt-1 text-xs text-slate-500">{status==='running'?'正在处理':status==='completed'?'阶段完成':status==='failed'?'阶段失败':status==='partial'?'部分完成':'等待执行'}</p></div></div>})}</div></Surface></div>
      <div className="space-y-4"><Surface className="p-5"><h2 className="text-sm font-semibold text-slate-950">任务信息</h2><dl className="mt-4 space-y-4"><Info label="来源" value={run.source_summary||'—'}/><Info label="运行账号" value={run.account_label}/><Info label="开始时间" value={formatDate(run.started_at)}/><Info label="结束时间" value={formatDate(run.finished_at)}/><div><dt className="text-xs text-slate-500">任务 ID</dt><dd className="mt-1 flex items-center gap-2"><code className="min-w-0 truncate text-xs text-slate-700">{run.run_id}</code><button title="复制任务 ID" onClick={()=>navigator.clipboard.writeText(run.run_id).then(()=>toast.success('已复制任务 ID'))} className="grid h-8 w-8 shrink-0 place-items-center rounded-md hover:bg-slate-100"><Clipboard className="h-4 w-4"/></button></dd></div></dl></Surface><Surface><button onClick={()=>setShowLogs(!showLogs)} className="flex min-h-14 w-full items-center justify-between px-5 text-sm font-semibold text-slate-900"><span className="flex items-center gap-2"><TerminalSquare className="h-4 w-4"/>技术日志</span><span className="text-xs font-normal text-slate-500">{logs.length} 条</span></button>{showLogs?<div className="max-h-96 overflow-auto border-t border-slate-200 bg-slate-950 p-4 font-mono text-xs leading-6 text-slate-300">{logs.length?logs.map((log,index)=><div key={String(log.id||log.source_event_id||index)}><span className="text-slate-500">{formatDate(String(log.created_at||log.synced_at||''))}</span> <span className="text-teal-300">[{String(log.level||'info')}]</span> {String(log.message||((log.payload as Item|undefined)?.message)||'')}</div>):<p className="text-slate-500">暂无日志</p>}</div>:null}</Surface><Surface className="p-5"><h2 className="text-sm font-semibold text-slate-950">任务项目</h2><p className="mt-1 text-xs text-slate-500">已记录 {items.length} 个阶段项目或同步实体。</p></Surface></div></div>
  </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-950">{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-medium text-slate-900">{value}</dd></div>}
